2.0 strings and vars
losalamos/Pavilion pull request #63
Opened 2018-10-24 22:57 UTC by pflarr

2018-10-25 17:12 UTC, nicholas-sly commented on lib/pavilion/pav_config.py
> +    os.environ.get(['PAV_CONFIG_DIR'], './'),
Shouldn't the user's configs override the installation-specific configs?

2018-10-25 17:12 UTC, nicholas-sly commented on lib/pavilion/schedulers/old_testconfig.py
> +        :param config:
Is this documentation incomplete?

2018-10-25 17:13 UTC, nicholas-sly commented on lib/pavilion/schedulers/old_testconfig.py
> +            if not isinstance(v, dict):
This seems to not do anything...

2018-10-25 17:37 UTC, nicholas-sly commented on lib/pavilion/config.py
> +    :param conf_type:
Documentation.

2018-10-25 17:38 UTC, nicholas-sly commented on lib/pavilion/config.py
> +    :param Union(str, None) host:
Documentation.

2018-10-25 17:38 UTC, nicholas-sly commented on lib/pavilion/config.py
> +        :param dict sched_vars: A
Documentation?

2018-10-25 17:46 UTC, nicholas-sly commented on lib/pavilion/pav_config.py
> +    Directories are searched in this order: $PAV_CONFIG_DIR, $USER/.pavilion, /etc/pavilion/,
Update to new order.

2018-10-25 17:55 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +# # variable name are optional.
Should the optional variables have specified defaults?

2018-10-25 17:57 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +                separator = end_str[1]
I may be severely lost, but is the precluding the possibility of a multi-character separator?

2018-10-25 17:59 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :param int start:
Documentation.

2018-10-25 18:00 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :param list tokens:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly requested changes
Minor nitpicks and questions.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :param dict iter_vars:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :return:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +                        break
done = True?

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :return:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/variables.py
> +    # The variable sets, in order of resolution priority.
Increasing priority?

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/variables.py
> +        :return:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :param list tokens:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +        :param int start:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +                separator = end_str[1]
I may be severely lost, but is the precluding the possibility of a multi-character separator?

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/string_parser.py
> +# # variable name are optional.
Should the optional variables have specified defaults?

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/schedulers/old_testconfig.py
> +            if not isinstance(v, dict):
This seems to not do anything...

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/schedulers/old_testconfig.py
> +        :param config:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/pav_config.py
> +    Directories are searched in this order: $PAV_CONFIG_DIR, $USER/.pavilion, /etc/pavilion/,
Update to new order.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/config.py
> +        :param dict sched_vars: A
Documentation?

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/config.py
> +    :param Union(str, None) host:
Documentation.

2018-10-25 20:23 UTC, nicholas-sly commented on lib/pavilion/config.py
> +    :param conf_type:
Documentation.

2018-10-26 16:55 UTC, pflarr commented on lib/pavilion/string_parser.py
> +                        break
The alternative is:
```suggestion
                        done = True
                        continue
```

2018-10-26 16:58 UTC, pflarr commented on lib/pavilion/schedulers/old_testconfig.py
> +        :param config:
This old code is around for reference only for now.

2018-10-26 16:59 UTC, pflarr commented on lib/pavilion/config.py
> +        :param dict sched_vars: A
I shouldn't have checked this file in yet. I wasn't anywhere near done.

2018-10-26 17:15 UTC, merged